# _config.yml

remote_theme: jekyll/midnight

plugins:
  - jekyll-seo-tag

include:
  - Gemfile

github_pages:
  jekyll:
    remote_theme:
      - jekyll/minima
      - jekyll/cayman
      - jekyll/primer
      - jekyll/tactile
      - jekyll/hacker
      - jekyll/leap-day
      - jekyll/midnight
      - jekyll/slate
      - jekyll/time-machine
      - jekyll/architect
      - jekyll/dinky
      - jekyll/hyde
      - jekyll/memoria
      - jekyll/merlot
      - jekyll/modernist
      - jekyll/siena
      - jekyll/tommy
      - jekyll/markdown-style
      - jekyll/contrast
      - jekyll/whiteglass
      - jekyll/moody
      - jekyll/very-sad
      - jekyll/forty
      - jekyll/overcast
      - jekyll/late-night
      - jekyll/midnight
      - jekyll/cayman-blog
      - jekyll/architect-blog

theme: minima
